version: 2


sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: suppliers
        freshness: 
          error_after:
            count: 120
            period: minute
          warn_after:
            count: 0
            period: minute
        loaded_at_field: updated_time
        
