version: 2

models:
  - name: stg_nation
    columns:
      - name: nationkey
        tests:
          - relationships:
              field: nationkey
              to: ref('stg_region')
        # tests:
        #   - unique
        #   - not_null
  - name: stg_region
    columns: 
      - name: name
        tests:
          - accepted_values:
              values:
                - "AFRICA"
                - "AMERICA"
                - "ASIA"
                - "EUROPE"
                - "MIDDLE EAST"
                