version: 2

models:
  - name: stg_nation        
    columns:
      - name: nationkey
        tests:
          - unique:
              config:
                store_failures: true
          - not_null:
              config:
                store_failures: false
      - name: regionkey
        tests:
          - relationships:
              field: regionkey
              to: ref('stg_region')
  - name: stg_region
    columns: 
      - name: name
        tests:
          - accepted_values:
              values:
                - "AFRICA"
                - "AMERICA"
                - "ASIA"
                - "EUROPE"
                - "MIDDLE EAST"


                